// TR lang variables

tinyMCE.addToLang('',{
bold_desc : 'Kalın (Ctrl+B)',
italic_desc : 'Yatık (Ctrl+I)',
underline_desc : 'Altı çizili (Ctrl+U)',
striketrough_desc : 'Üzeri çizili',
justifyleft_desc : 'Sola hizala',
justifycenter_desc : 'Ortala',
justifyright_desc : 'Sağa hizala',
justifyfull_desc : 'İki yana hizala',
bullist_desc : 'Sıralanmamış liste',
numlist_desc : 'Sıralı liste',
outdent_desc : 'Girintiyi azalt',
indent_desc : 'Girintiyi artır',
undo_desc : 'Geri al (Ctrl+Z)',
redo_desc : 'İleri al (Ctrl+Y)',
link_desc : 'Bağlantı ekle/düzenle',
unlink_desc : 'Bağlantıyı kaldır',
image_desc : 'Resim ekle/düzenle',
cleanup_desc : 'Dağınık kodu temizle',
focus_alert : 'Bu komutu kullanmadan önce editör odaklanmalı.',
edit_confirm : 'Bu metin alanı için WYSIWYG modunu kullanmak istiyor musunuz?',
insert_link_title : 'Bağlantı ekle/düzenle',
insert : 'Ekle',
update : 'Güncelle',
cancel : 'Vazgeç',
insert_link_url : 'Bağlantı yolu',
insert_link_target : 'Hedef',
insert_link_target_same : 'Bağlantıyı aynı pencerede aç',
insert_link_target_blank : 'Bağlantıyı yeni bir pencerede aç',
insert_image_title : 'Resim ekle/düzenle',
insert_image_src : 'Resim ekle',
insert_image_alt : 'Resim açıklaması',
help_desc : 'Yardım',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopyala/Kes/Yapıştır Mozilla ve Firefox tarayıcıları için mevcut değil.\nBu konuda daha fazla bilgi istiyor musunuz?',
popup_blocked : 'Üzgünüz, açılır pencere (pop-up) engelleyiciniz uygulama için gerekli olan bir pencerenin açılmasını engelliyor. Bu aracı tam olarak kullanmak istiyorsanız bu site için açılır pencere engelleyicisini devre dışı bırakmalısınız.'
});
