// TR lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Genel',
popup_tab : 'Popup',
events_tab : 'Olaylar',
advanced_tab : 'Gelişmiş',
general_props : 'Genel özellikler',
popup_props : 'Popup özellikleri',
event_props : 'Olaylar',
advanced_props : 'Gelişmiş özellikler',
popup_opts : 'Seçenekler',
anchor_names : 'Çapa noktaları',
target_same : 'Pencerede/çerçevede aç',
target_parent : 'Bir üst pencere/çerçevede aç',
target_top : 'En üst çerçevede aç (tüm çerçeveleri değiştirir)',
target_blank : 'Yeni pencerede aç',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Pencere ismi',
popup_return : 'Yerleştir \'return false\'',
popup_scrollbars : 'Kaydırma çubuklarını göster',
popup_statusbar : 'Durum çubuğunu göster',
popup_toolbar : 'Araç çubuklarını göster',
popup_menubar : 'Menü çubuğunu göster',
popup_location : 'Konum çubuğunu göster',
popup_resizable : 'Pencereyi boyutlandırılabilir yap',
popup_dependent : 'Bağımlı (sadece Mozilla/Firefox)',
popup_size : 'Boyut',
popup_position : 'Konum (X/Y)',
id : 'Id',
style: 'Style',
classes : 'Sınıflar',
target_name : 'Hedef ismi',
langdir : 'Yazı yönü',
target_langcode : 'Hedef dil kodu',
langcode : 'Dil kodu',
encoding : 'Hedef karakter kodlaması',
mime : 'Hedef MIME tipi',
rel : 'Relationship page to target',
rev : 'Relationship target to page',
tabindex : 'SekmeDizini',
accesskey : 'ErişimAnahtarı',
ltr : 'Soldan sağa',
rtl : 'Sağdam sola'
});
