// TR lang variables

tinyMCE.addToLang('style',{
title : 'CSS Stilini düzenle',
styleinfo_desc : 'CSS Stilini düzenle',
text_tab : 'Yazı',
background_tab : 'Arkaplan',
block_tab : 'Blok',
box_tab : 'Box',
border_tab : 'Kenar',
list_tab : 'Liste',
positioning_tab : 'Konumlandırma',
text_props : 'Yazı',
text_font : 'Yazı tipi',
text_size : 'Boyut',
text_weight : 'Kalınlık',
text_style : 'Stil',
text_variant : 'Değişken',
text_lineheight : 'Satır yüksekliği',
text_case : 'Durum',
text_color : 'Renk',
text_decoration : 'Dekorasyon',
background_color : 'Zemin rengi',
background_image : 'Arkaplan resmi',
background_repeat : 'Tekrarla',
background_attachment : 'Eklenti',
background_hpos : 'Yatay yerleşim',
background_vpos : 'Dikey yerleşim',
block_wordspacing : 'Kelimeler arası boşluklar',
block_letterspacing : 'Harfler arası boşluklar',
block_vertical_alignment : 'Dikey hizalama',
block_text_align : 'Yazı hizalaması',
block_text_indent : 'Yazı girintisi',
block_whitespace : 'Boşluk',
block_display : 'Görüntü',
box_width : 'Genişlik',
box_height : 'Yükseklik',
box_float : 'Float',
box_clear : 'Clear',
padding : 'Kaydırma',
same : 'Hepsi için aynı',
top : 'Üst',
right : 'Sağ',
bottom : 'Alt',
left : 'Sol',
margin : 'Kenar boşlukları',
style : 'Stil',
width : 'Genişlik',
height : 'Yükseklik',
color : 'Renk',
list_type : 'Tür',
bullet_image : 'Bullet image',
position : 'Konumlandırma',
positioning_type : 'Tür',
visibility : 'Görünürlülük',
zindex : 'Z-index',
overflow : 'Taşma',
placement : 'Yerleşim',
clip : 'Kırpma'
});
