#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2009 TÜBİTAK UEKAE
# Licensed under the GNU General Public License, version 3.
# See the file http://www.gnu.org/copyleft/gpl.txt.

DVDCLIENTS_PER_PAGE = 100
DVD_MAIL_LIST = "cdgonder@liste.ozgurlukicin.com"
CITY_LIST = (
    ('adana','Adana'),
    ('adiyaman','Adıyaman'),
    ('afyon','Afyon'),
    ('agri','Ağrı'),
    ('aksaray','Aksaray'),
    ('amasya','Amasya'),
    ('ankara','Ankara'),
    ('antalya','Antalya'),
    ('ardahan','Ardahan'),
    ('artvin','Artvin'),
    ('aydin','Aydın'),
    ('balikesir','Balikesir'),
    ('bartin','Bartın'),
    ('batman','Batman'),
    ('bayburt','Bayburt'),
    ('bilecik','Bilecik'),
    ('bingol','Bingöl'),
    ('bitlis','Bitlis'),
    ('bolu','Bolu'),
    ('burdur','Burdur'),
    ('bursa','Bursa'),
    ('canakkale','Çanakkale'),
    ('cankiri','Çankırı'),
    ('corum','Çorum'),
    ('denizli','Denizli'),
    ('diyarbakir','Diyarbakır'),
    ('duzce','Düzce'),
    ('edirne','Edirne'),
    ('elazig','Elazığ'),
    ('erzincan','Erzincan'),
    ('erzurum','Erzurum'),
    ('eskisehir','Eskişehir'),
    ('gaziantep','Gaziantep'),
    ('giresun','Giresun'),
    ('gumushane','Gümüşhane'),
    ('hakkari','Hakkari'),
    ('hatay','Hatay'),
    ('igdir','Iğdır'),
    ('isparta','Isparta'),
    ('istanbul_anadolu','İstanbul (Anadolu)'),
    ('istanbul_avrupa','İstanbul (Avrupa)'),
    ('izmir','İzmir'),
    ('kahramanmaras','KahramanMaraş'),
    ('karabuk', 'Karabük'),
    ('karaman','Karaman'),
    ('kars','Kars'),
    ('kastamonu','Kastamonu'),
    ('kayseri','Kayseri'),
    ('kilis', 'Kilis'),
    ('kirikkale','Kırıkkale'),
    ('kirklareli','Kırklareli'),
    ('kirsehir','Kırşehir'),
    ('kocaeli','Kocaeli'),
    ('konya','Konya'),
    ('kutahya','Kütahya'),
    ('malatya','Malatya'),
    ('manisa','Manisa'),
    ('mardin','Mardin'),
    ('mersin','Mersin'),
    ('mugla','Muğla'),
    ('mus','Muş'),
    ('nevsehir','Nevşehir'),
    ('nigde','Niğde'),
    ('ordu','Ordu'),
    ('osmaniye', 'Osmaniye'),
    ('rize','Rize'),
    ('sakarya','Sakarya'),
    ('samsun','Samsun'),
    ('siirt','Siirt'),
    ('sinop','Sinop'),
    ('sirnak','Şırnak'),
    ('sivas','Sivas'),
    ('tekirdag','Tekirdag'),
    ('tokat','Tokat'),
    ('trabzon','Trabzon'),
    ('tunceli','Tunceli'),
    ('urfa','Şanlıurfa'),
    ('usak','Uşak'),
    ('van','Van'),
    ('yalova', 'Yalova'),
    ('yozgat','Yozgat'),
    ('zonguldak','Zonguldak'),
    #('zzyurtdisi', 'Yurtdışı'),
)
