// TR lang variables

tinyMCE.addToLang('table',{
general_tab : 'Genel',
advanced_tab : 'Gelişmiş',
general_props : 'Genel özellikler',
advanced_props : 'Gelişmiş özellikler',
desc : 'Yeni bir tablo ekle',
row_before_desc : 'Satır ekle, önce',
row_after_desc : 'Satır ekle, sonra',
delete_row_desc : 'Satır sil',
col_before_desc : 'Sütün ekle, önce',
col_after_desc : 'Sütün ekle, sonra',
delete_col_desc : 'Sütün sil',
rowtype : 'Tablo kısmındaki satır',
title : 'Tablo Ekle/Düzenle',
width : 'Genişlik',
height : 'Yükseklik',
cols : 'Sütünlar',
rows : 'Satırlar',
cellspacing : 'Hücre aralığı',
cellpadding : 'Hücre kaydırma',
border : 'Kenarlık',
align : 'Hizalama',
align_default : 'Öntanımlı',
align_left : 'Sol',
align_right : 'Sağ',
align_middle : 'Orta',
row_title : 'Tablo satır özellikleri',
cell_title : 'Tablo hücre özellikleri',
cell_type : 'Hücre türü',
row_desc : 'Tablo satır özellikleri',
cell_desc : 'Tablo hücre özellikleri',
valign : 'Dikey hizalama',
align_top : 'Üst',
align_bottom : 'Alt',
props_desc : 'Tablo özellikleri',
bordercolor : 'Kenarlık rengi',
bgcolor : 'Arkaplan rengi',
merge_cells_title : 'Hücreleri birleştir',
split_cells_desc : 'Hücreleri böl',
merge_cells_desc : 'Hücreleri birleştir',
cut_row_desc : 'Satırı kes',
copy_row_desc : 'Satırı kopyala',
paste_row_before_desc : 'Satırı yapıştır, önce',
paste_row_after_desc : 'Satırı yapıştır, sonra',
id : 'Id',
style: 'Stil',
langdir : 'Yazı yönü',
langcode : 'Dil kodu',
mime : 'Hedef MIME türü',
ltr : 'Soldan sağa',
rtl : 'Sağdan sola',
bgimage : 'Arkaplan resmi',
summary : 'Özet',
td : "Veri",
th : "Başlık",
cell_cell : 'Geçerli hücreyi güncelle',
cell_row : 'Satırdaki tüm hücreleri güncelle',
cell_all : 'Tablodaki tüm hücreleri güncelle',
row_row : 'Geçerli satırı güncelle',
row_odd : 'Tablodaki tekil satırları güncelle',
row_even : 'Tablodaki çift satırları güncelle',
row_all : 'Tablodaki tüm satırları güncelle',
thead : 'Tablo başlığı',
tbody : 'Tablo gövdesi',
tfoot : 'Tablo altlığı',
del : 'Tablo sil',
scope : 'Konu',
row : 'Satır',
col : 'Sütün',
rowgroup : 'Satır Grubu',
colgroup : 'Sütün Grubu',
col_limit : 'En yüksek sütün sayısı olan {$cols}\'yı aştınız.'
row_limit : 'En yüksek satır sayısı olan {$rows}\'yı aştınız.'
cell_limit : 'En yüksek hücre sayısı olan {$cells}\'yı aştınız.'
missing_scope : 'Bu tablo için konu belirlemeden devam etmek istediğinize emin misiniz? Konu kısmı olmadan tablo içeriğinin anlaşılması zor olabilir.'
});
