tinyMCE.init({
    mode : "textareas",
    theme : "advanced",
    theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
    theme_advanced_buttons2 : "",
    theme_advanced_buttons3 : "",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_path_location : "bottom",
    browsers : "msie,gecko,opera,safari",
    content_css : "/media/css/new/forum_topic.css",
    dialog_type : "modal",
    entity_encoding : "raw",
    relative_urls : false,
    convert_urls : false,
    width : "630",
    height : "300",
    extended_valid_elements : "a[name|href|target|title],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|name|style],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
    advimage_update_dimensions_onchange: true,
    plugins : "advimage,autosave,searchreplace,table,visualchars,advlink,emotions,media,preview,safari,style,template,xhtmlxtras",
    gecko_spellcheck : true,
    language : "tr"
});
