// TR lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stil --',
theme_code_desc : 'HTML kaynağını düzenle',
theme_code_title : 'HTML kaynak düzenleyici',
theme_code_wordwrap : 'Sözcük kaydırma',
theme_sub_desc : 'Altyazı',
theme_sup_desc : 'Üstyazı',
theme_hr_desc : 'Yatay cetvel ekle',
theme_removeformat_desc : 'Biçimi kaldır',
theme_custom1_desc : 'Özel açıklamanız buraya',
insert_image_border : 'Kenarlık',
insert_image_dimensions : 'Boyutlar',
insert_image_vspace : 'Dikey boşluk',
insert_image_hspace : 'Yatay boşluk',
insert_image_align : 'Hizalama',
insert_image_align_default : '-- Seçilmedi --',
insert_image_align_baseline : 'Taban çizgisine',
insert_image_align_top : 'Üst',
insert_image_align_middle : 'Orta',
insert_image_align_bottom : 'Alt',
insert_image_align_texttop : 'YazıÜstü',
insert_image_align_absmiddle : 'Mutlak Orta',
insert_image_align_absbottom : 'Mutlak Alt',
insert_image_align_left : 'Sol',
insert_image_align_right : 'Sağ',
theme_font_size : '-- Yazı tipi boyutu --',
theme_fontdefault : '-- Yazı Tipi --',
theme_block : '-- Biçim --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adres',
theme_pre : 'Biçimlendirilmiş',
theme_h1 : 'Başlık 1',
theme_h2 : 'Başlık 2',
theme_h3 : 'Başlık 3',
theme_h4 : 'Başlık 4',
theme_h5 : 'Başlık 5',
theme_h6 : 'Başlık 6',
theme_blockquote : 'Blockquote',
theme_code : 'Kod',
theme_samp : 'Kod örneği',
theme_dt : 'Terim tanımlaması ',
theme_dd : 'Tanım açıklaması',
theme_colorpicker_title : 'Renk seçin',
theme_colorpicker_apply : 'Uygula',
theme_forecolor_desc : 'Yazı rengi seçin',
theme_backcolor_desc : 'Zemin rengi seçin',
theme_charmap_title : 'Özel karakter seçin',
theme_charmap_desc : 'Özel karakter ekle',
theme_visualaid_desc : 'Rehber çizileri/görünmez elemanları Aç/Kapa',
insert_anchor_title : 'Çapa Ekle/Düzenle',
insert_anchor_name : 'Çapa ismi',
theme_anchor_desc : 'Çapa Ekle/Düzenle',
theme_insert_link_titlefield : 'Başlık',
theme_clipboard_msg : 'Kopyalama/Kesme/Yapıştırma Mozilla ve Firefox\'ta mecvut değildir.\nBu konu hakkında daha fazla bilgi ister misiniz?',
theme_path : 'Yol',
cut_desc : 'Kes',
copy_desc : 'Kopyala',
paste_desc : 'Yapıştır',
link_list : 'Bağlantı listesi',
image_list : 'Resim listesi',
browse : 'Gözat',
image_props_desc : 'Resim özellikleri',
newdocument_desc : 'Yeni belge',
class_name : 'Sınıf',
newdocument : 'Tüm içeriği silmek istediğinize emin misiniz?',
about_title : 'TinyMCE Hakkında',
about : 'Hakkında',
license : 'Lisans',
plugins : 'Eklentiler',
plugin : 'Eklenti',
author : 'Yazar',
version : 'Version',
loaded_plugins : 'Yüklenmiş eklentiler',
help : 'Yardım',
not_set : '-- Seçilmemiş --',
close : 'Kapat',
toolbar_focus : 'Araç tuşlarına geç - Alt+Q, Editöre geç - Alt-Z, Bileşen yoluna geç - Alt-X'
});
