tinyMCE.addI18n('tr.advanced',{
style_select:"Biçemler",
font_size:"Yazıtipi boyutu",
fontdefault:"Yazıtipi ailesi",
block:"Biçim",
paragraph:"Paragraf",
div:"Bölüm",
address:"Adres",
pre:"Önceden biçimlendirilmiş",
h1:"Başlık 1",
h2:"Başlık 2",
h3:"Başlık 3",
h4:"Başlık 4",
h5:"Başlık 5",
h6:"Başlık 6",
blockquote:"Blok alıntı",
code:"Kod",
samp:"Kod örneği",
dt:"Tanım terimi ",
dd:"Tanım açıklaması",
bold_desc:"Kalın (Ctrl+B)",
italic_desc:"Eğil (Ctrl+I)",
underline_desc:"Altıçizili (Ctrl+U)",
striketrough_desc:"Üstüçizili",
justifyleft_desc:"Sola daya",
justifycenter_desc:"Ortala",
justifyright_desc:"Sağa daya",
justifyfull_desc:"İki yana yasla",
bullist_desc:"Madde imli liste",
numlist_desc:"Sıralı list",
outdent_desc:"Çıkıntıla",
indent_desc:"Girintile",
undo_desc:"Geri al (Ctrl+Z)",
redo_desc:"Yinele (Ctrl+Y)",
link_desc:"Köprü ekle/düzenle",
unlink_desc:"Köprüyü kaldır",
image_desc:"Resim ekle/düzenle",
cleanup_desc:"Düzensiz kodları düzene sok",
code_desc:"HTML kaynağını düzenle",
sub_desc:"Satır altı",
sup_desc:"Satır üstü",
hr_desc:"Yatay çizgi ekle",
removeformat_desc:"Biçimlendirmeyi kaldır",
custom1_desc:"Açıklamanızı yazın",
forecolor_desc:"Metin rengini seç",
backcolor_desc:"Zemin rengini seç",
charmap_desc:"Özel karakter ekle",
visualaid_desc:"Kılavuz çizgileri ve görünmez öğeleri göster-gizle",
anchor_desc:"Köprü ekle/düzenle",
cut_desc:"Kes",
copy_desc:"Kopyala",
paste_desc:"Yapıştır",
image_props_desc:"Resim özellikleri",
newdocument_desc:"Yeni belge",
help_desc:"Yardım",
blockquote_desc:"Blok alıntı",
clipboard_msg:"Kes/Kopyala/Yapıştır Mozilla ve Firefox'da kullanılabilir değildir.\r\nBu konuda daha fazla bilgi almak ister misiniz?",
path:"Yol",
newdocument:"Tüm içeriği kaldırmak istediğinize emin misiniz??",
toolbar_focus:"Araç düğmelerine geç - Alt+Q, Editöre geç - Alt-Z, Öğe yoluna geç - Alt-X",
more_colors:"Daha fazla renk"
});
