tinyMCE.addI18n('tr.advanced_dlg',{
about_title:"TinyMCE Hakkında",
about_general:"Hakkında",
about_help:"Yardım",
about_license:"Lisans",
about_plugins:"Eklentiler",
about_plugin:"Eklenti",
about_author:"Yazar",
about_version:"Sürüm",
about_loaded:"Yüklü eklentiler",
anchor_title:"Köprü ekle/düzenle",
anchor_name:"Köprü adı",
code_title:"HTML Kaynak Editörü",
code_wordwrap:"Kelime kaydırma",
colorpicker_title:"Renk seçin",
colorpicker_picker_tab:"Seçici",
colorpicker_picker_title:"Renk seçici",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet renkleri",
colorpicker_named_tab:"Adlı",
colorpicker_named_title:"Adı olan renkler",
colorpicker_color:"Renk:",
colorpicker_name:"Ad:",
charmap_title:"Özel karakter seç",
image_title:"Resim ekle/düzenle",
image_src:"Resim adresi",
image_alt:"Resim açıklaması",
image_list:"Resim listesi",
image_border:"Çerçeve",
image_dimensions:"Boyutlar",
image_vspace:"Dikey boşluk",
image_hspace:"Yatay boşluk",
image_align:"Yerleşim",
image_align_baseline:"Temel hat",
image_align_top:"Üste",
image_align_middle:"Ortaya",
image_align_bottom:"Alta",
image_align_texttop:"Metin üstüne",
image_align_textbottom:"Metin altına",
image_align_left:"Sola",
image_align_right:"Sağa",
link_title:"Köprü ekle/düzenle",
link_url:"Köprü adresi",
link_target:"Hedef",
link_target_same:"Köprüyü aynı pencerede aç",
link_target_blank:"Köprüyü yeni pencerede aç",
link_titlefield:"Başlık",
link_is_email:"Girdiğiniz adres bir e-posta adresine benziyor, gereken mailto: önekini eklemek ister misiniz?",
link_is_external:"Girdiğiniz adres harici bir köprüye benziyor, gereken http:// önekini eklemek ister misiniz?",
link_list:"Köprü listesi"
});
